# -*- coding: utf-8 -*-
# Generated by Afaan Oromoo transpiler

x = 10
y = (x + (5 * 2))
if (x > 5):
    print(x)
else:
    print(0)
while (x < 10):
    x = (x + 1)
def ida_uu(a, b):
    return (a + b)

print(ida_uu(3, 4))
