"""AST visitor that emits indented Python 3 source."""

from __future__ import annotations

from pathlib import Path
from typing import List

from ..parser.ast import (
    Assign,
    BinaryOp,
    Boolean,
    ExprStmt,
    Expression,
    FunctionCall,
    FunctionDef,
    Identifier,
    If,
    Import,
    Number,
    Program,
    Return,
    Statement,
    While,
)
from ..utils.modules import normalize_import_spec, python_module_name
from ..utils.names import to_python_name


class PythonGenerator:
    """Walks the AST and produces executable Python code."""

    INDENT = "    "

    def __init__(self) -> None:
        self._lines: List[str] = []
        self._indent_level = 0

    def generate(self, program: Program) -> str:
        self._lines = ["# -*- coding: utf-8 -*-", "# Generated by Afaan Oromoo transpiler", ""]
        self._indent_level = 0

        for stmt in program.statements:
            if isinstance(stmt, Import):
                mod = python_module_name(
                    Path(normalize_import_spec(stmt.module)), is_entry=False
                )
                self._lines.append(f"from {mod} import *")

        if any(isinstance(s, Import) for s in program.statements):
            self._lines.append("")

        for stmt in program.statements:
            if not isinstance(stmt, Import):
                self._emit_statement(stmt)
        return "\n".join(self._lines) + "\n"

    def _indent(self) -> str:
        return self.INDENT * self._indent_level

    def _write(self, line: str) -> None:
        self._lines.append(self._indent() + line)

    def _emit_statement(self, stmt: Statement) -> None:
        if isinstance(stmt, Assign):
            self._write(f"{to_python_name(stmt.name)} = {self._emit_expression(stmt.value)}")
        elif isinstance(stmt, If):
            self._emit_if(stmt)
        elif isinstance(stmt, While):
            self._emit_while(stmt)
        elif isinstance(stmt, FunctionDef):
            self._emit_function_def(stmt)
        elif isinstance(stmt, Return):
            self._write(f"return {self._emit_expression(stmt.value)}")
        elif isinstance(stmt, ExprStmt):
            self._write(self._emit_expression(stmt.expression))

    def _emit_if(self, node: If) -> None:
        self._write(f"if {self._emit_expression(node.condition)}:")
        self._indent_level += 1
        for s in node.then_body:
            self._emit_statement(s)
        self._indent_level -= 1
        if node.else_body is not None:
            self._write("else:")
            self._indent_level += 1
            for s in node.else_body:
                self._emit_statement(s)
            self._indent_level -= 1

    def _emit_while(self, node: While) -> None:
        self._write(f"while {self._emit_expression(node.condition)}:")
        self._indent_level += 1
        for s in node.body:
            self._emit_statement(s)
        self._indent_level -= 1

    def _emit_function_def(self, node: FunctionDef) -> None:
        params = ", ".join(to_python_name(p) for p in node.params)
        self._write(f"def {to_python_name(node.name)}({params}):")
        self._indent_level += 1
        for s in node.body:
            self._emit_statement(s)
        self._indent_level -= 1
        self._lines.append("")

    def _emit_expression(self, expr: Expression) -> str:
        if isinstance(expr, Number):
            if isinstance(expr.value, float):
                return repr(expr.value)
            return str(expr.value)
        if isinstance(expr, Boolean):
            return "True" if expr.value else "False"
        if isinstance(expr, Identifier):
            return to_python_name(expr.name)
        if isinstance(expr, BinaryOp):
            left = self._emit_expression(expr.left)
            right = self._emit_expression(expr.right)
            if expr.op == "-":
                return f"({left} - {right})"
            return f"({left} {expr.op} {right})"
        if isinstance(expr, FunctionCall):
            return self._emit_function_call(expr)
        raise TypeError(f"Unknown expression type: {type(expr)}")

    def _emit_function_call(self, node: FunctionCall) -> str:
        args = ", ".join(self._emit_expression(a) for a in node.args)
        if node.name == "maxxansi":
            return f"print({args})"
        return f"{to_python_name(node.name)}({args})"
