"""AST visitor that emits indented Python 3 source."""

from __future__ import annotations

from pathlib import Path
from typing import List

from ..lexer.tokens import python_keyword_for_word
from ..parser.ast import (
    Assert,
    Assign,
    Await,
    BinaryOp,
    Boolean,
    Break,
    ClassDef,
    Continue,
    Del,
    ExprStmt,
    Expression,
    ForLoop,
    FunctionCall,
    FunctionDef,
    GlobalStmt,
    Identifier,
    If,
    Import,
    NoneLiteral,
    NonlocalStmt,
    Number,
    Pass,
    Program,
    Raise,
    Return,
    Statement,
    TryStmt,
    UnaryOp,
    While,
    With,
    Yield,
)
from ..utils.modules import normalize_import_spec, python_module_name
from ..utils.names import to_python_name


class PythonGenerator:
    """Walks the AST and produces executable Python code."""

    INDENT = "    "

    def __init__(self) -> None:
        self._lines: List[str] = []
        self._indent_level = 0

    def generate(self, program: Program) -> str:
        self._lines = ["# -*- coding: utf-8 -*-", "# Generated by Afaan Oromoo transpiler", ""]
        self._indent_level = 0

        imports = [s for s in program.statements if isinstance(s, Import)]
        for stmt in imports:
            self._emit_import(stmt)
        if imports:
            self._lines.append("")

        for stmt in program.statements:
            if not isinstance(stmt, Import):
                self._emit_statement(stmt)
        return "\n".join(self._lines) + "\n"

    def _emit_import(self, node: Import) -> None:
        mod = python_module_name(
            Path(normalize_import_spec(node.module)), is_entry=False
        )
        if node.kind == "import":
            self._lines.append(f"import {mod}")
        else:
            self._lines.append(f"from {mod} import *")

    def _indent(self) -> str:
        return self.INDENT * self._indent_level

    def _write(self, line: str) -> None:
        self._lines.append(self._indent() + line)

    def _emit_statement(self, stmt: Statement) -> None:
        if isinstance(stmt, Assign):
            self._write(f"{to_python_name(stmt.name)} = {self._emit_expression(stmt.value)}")
        elif isinstance(stmt, If):
            self._emit_if(stmt)
        elif isinstance(stmt, While):
            self._emit_while(stmt)
        elif isinstance(stmt, ForLoop):
            self._emit_for(stmt)
        elif isinstance(stmt, TryStmt):
            self._emit_try(stmt)
        elif isinstance(stmt, FunctionDef):
            self._emit_function_def(stmt)
        elif isinstance(stmt, ClassDef):
            self._emit_class_def(stmt)
        elif isinstance(stmt, Return):
            if stmt.value is None:
                self._write("return")
            else:
                self._write(f"return {self._emit_expression(stmt.value)}")
        elif isinstance(stmt, ExprStmt):
            self._write(self._emit_expression(stmt.expression))
        elif isinstance(stmt, Break):
            self._write("break")
        elif isinstance(stmt, Continue):
            self._write("continue")
        elif isinstance(stmt, Pass):
            self._write("pass")
        elif isinstance(stmt, GlobalStmt):
            names = ", ".join(to_python_name(n) for n in stmt.names)
            self._write(f"global {names}")
        elif isinstance(stmt, NonlocalStmt):
            names = ", ".join(to_python_name(n) for n in stmt.names)
            self._write(f"nonlocal {names}")
        elif isinstance(stmt, Raise):
            if stmt.expression is None:
                self._write("raise")
            else:
                self._write(f"raise {self._emit_expression(stmt.expression)}")
        elif isinstance(stmt, Assert):
            self._write(f"assert {self._emit_expression(stmt.condition)}")
        elif isinstance(stmt, Del):
            self._write(f"del {self._emit_expression(stmt.target)}")
        elif isinstance(stmt, Yield):
            if stmt.value is None:
                self._write("yield")
            else:
                self._write(f"yield {self._emit_expression(stmt.value)}")
        elif isinstance(stmt, With):
            self._emit_with(stmt)

    def _emit_if(self, node: If) -> None:
        self._write(f"if {self._emit_expression(node.condition)}:")
        self._indent_level += 1
        for s in node.then_body:
            self._emit_statement(s)
        self._indent_level -= 1
        for branch in node.elif_branches:
            self._write(f"elif {self._emit_expression(branch.condition)}:")
            self._indent_level += 1
            for s in branch.body:
                self._emit_statement(s)
            self._indent_level -= 1
        if node.else_body is not None:
            self._write("else:")
            self._indent_level += 1
            for s in node.else_body:
                self._emit_statement(s)
            self._indent_level -= 1

    def _emit_while(self, node: While) -> None:
        self._write(f"while {self._emit_expression(node.condition)}:")
        self._indent_level += 1
        for s in node.body:
            self._emit_statement(s)
        self._indent_level -= 1

    def _emit_for(self, node: ForLoop) -> None:
        target = to_python_name(node.target)
        self._write(f"for {target} in {self._emit_expression(node.iterable)}:")
        self._indent_level += 1
        for s in node.body:
            self._emit_statement(s)
        self._indent_level -= 1

    def _emit_try(self, node: TryStmt) -> None:
        self._write("try:")
        self._indent_level += 1
        for s in node.body:
            self._emit_statement(s)
        self._indent_level -= 1
        for handler in node.handlers:
            if handler.exc_type:
                exc = to_python_name(handler.exc_type)
                self._write(f"except {exc}:")
            else:
                self._write("except:")
            self._indent_level += 1
            for s in handler.body:
                self._emit_statement(s)
            self._indent_level -= 1
        if node.finally_body is not None:
            self._write("finally:")
            self._indent_level += 1
            for s in node.finally_body:
                self._emit_statement(s)
            self._indent_level -= 1

    def _emit_function_def(self, node: FunctionDef) -> None:
        prefix = "async " if node.is_async else ""
        params = ", ".join(to_python_name(p) for p in node.params)
        self._write(f"{prefix}def {to_python_name(node.name)}({params}):")
        self._indent_level += 1
        for s in node.body:
            self._emit_statement(s)
        self._indent_level -= 1
        self._lines.append("")

    def _emit_class_def(self, node: ClassDef) -> None:
        self._write(f"class {to_python_name(node.name)}:")
        self._indent_level += 1
        if not node.body:
            self._write("pass")
        else:
            for s in node.body:
                self._emit_statement(s)
        self._indent_level -= 1
        self._lines.append("")

    def _emit_with(self, node: With) -> None:
        self._write(f"with {self._emit_expression(node.context)}:")
        self._indent_level += 1
        for s in node.body:
            self._emit_statement(s)
        self._indent_level -= 1

    def _emit_expression(self, expr: Expression) -> str:
        if isinstance(expr, Number):
            if isinstance(expr.value, float):
                return repr(expr.value)
            return str(expr.value)
        if isinstance(expr, Boolean):
            return "True" if expr.value else "False"
        if isinstance(expr, NoneLiteral):
            return "None"
        if isinstance(expr, Identifier):
            return to_python_name(expr.name)
        if isinstance(expr, UnaryOp):
            return f"({expr.op} {self._emit_expression(expr.operand)})"
        if isinstance(expr, Await):
            return f"await {self._emit_expression(expr.expression)}"
        if isinstance(expr, BinaryOp):
            left = self._emit_expression(expr.left)
            right = self._emit_expression(expr.right)
            if expr.op == "-":
                return f"({left} - {right})"
            return f"({left} {expr.op} {right})"
        if isinstance(expr, FunctionCall):
            return self._emit_function_call(expr)
        raise TypeError(f"Unknown expression type: {type(expr)}")

    def _emit_function_call(self, node: FunctionCall) -> str:
        args = ", ".join(self._emit_expression(a) for a in node.args)
        py_name = python_keyword_for_word(node.name) or to_python_name(node.name)
        if node.name == "maxxansi":
            return f"print({args})"
        return f"{py_name}({args})"
